# Training parameters
epochs: 20
batch_size: 1024 
val_batch_size: 256 
lr: 0.0005
weight_decay: 0.0001

# Model parameters
in_channels: 3
base_channels: 64
time_dim: 256

# Diffusion parameters
timesteps: 1000
sample_steps: 100

# Data parameters
train_sigma_min: 0.0
train_sigma_max: 50.0
val_sigma: 25.0

# Other parameters
num_workers: 24
save_path: "cifar10_cond_diffusion_new.pth"